name: Deploy to GitHub Pages
on:
  push:
    branches: [main]  # Change to your source branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Copy files to deployment folder
        run: |
          mkdir public
          cp -r Mini challenge 2/* public/   # Replace "web" with your subfolder name

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
